import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {EditorState} from '@codemirror/state';
import {EditorView, keymap, lineNumbers, highlightActiveLineGutter, highlightSpecialChars, drawSelection, dropCursor, rectangularSelection, crosshairCursor, highlightActiveLine} from '@codemirror/view';
import {defaultKeymap, history, historyKeymap} from '@codemirror/commands';
import {javascript} from '@codemirror/lang-javascript';
import {syntaxHighlighting, defaultHighlightStyle, bracketMatching} from '@codemirror/language';
import {autocompletion, completionKeymap, closeBrackets, closeBracketsKeymap} from '@codemirror/autocomplete';
import {Search, Undo2, Redo2, Download, Play, ChevronDown, ChevronRight, FileText, Layers3, Settings, BookOpen, PencilRuler, Plus, MoreHorizontal, Lock, Eye, CircleDot, Link2, Type, ZoomIn, ZoomOut, Maximize, Grid3X3, Magnet, PanelRightClose, Sparkles, Save, FolderOpen, Share2, Command, CheckCircle2} from 'lucide-react';
import './styles.css';

const initialDoc=`// Motivo floreale — pagina 1\nring ring_center\nring_center.totalNodes = 16\nring_center.position = point(420, 280)\nring_center.roundness = 58\nring_center.style.stroke = "#6750A4"\nring_center.attachments = composition("4-4-4-4")\n\npicot p_top\np_top.parent = ring_center\np_top.afterNode = 4\np_top.length = 2U\np_top.joinable = true\n\nchain chain_right\nchain_right.from = ring_center.attachment(4)\nchain_right.to = point(590, 280)\nchain_right.totalNodes = 10\nchain_right.curvature = 32\n\nring ring_right\nring_right.totalNodes = 12\nring_right.position = point(640, 280)\nring_right.rotate(18)`;

const pages=[{name:'Motivo principale',count:4},{name:'Bordo esterno',count:12},{name:'Dettagli',count:6}];
const objects=[{id:'ring_center',kind:'Ring',icon:CircleDot,color:'#6750a4'},{id:'p_top',kind:'Picot',icon:Sparkles,color:'#b3261e'},{id:'chain_right',kind:'Chain',icon:Link2,color:'#365f54'},{id:'ring_right',kind:'Ring',icon:CircleDot,color:'#6750a4'}];

function CodeEditor(){const host=useRef(null); useEffect(()=>{const state=EditorState.create({doc:initialDoc,extensions:[lineNumbers(),highlightActiveLineGutter(),highlightSpecialChars(),history(),drawSelection(),dropCursor(),EditorState.allowMultipleSelections.of(true),javascript(),syntaxHighlighting(defaultHighlightStyle),bracketMatching(),closeBrackets(),autocompletion({override:[ctx=>{const word=ctx.matchBefore(/\w*/); if(!word||word.from===word.to&&!ctx.explicit)return null; return {from:word.from,options:['ring','chain','picot','point','totalNodes','position','roundness','rotate','attachment'].map(label=>({label,type:'keyword'}))}}]}),rectangularSelection(),crosshairCursor(),highlightActiveLine(),keymap.of([...closeBracketsKeymap,...defaultKeymap,...historyKeymap,...completionKeymap]),EditorView.theme({'&':{height:'100%',fontSize:'13px',backgroundColor:'#292725',color:'#ede9e4'},'.cm-content':{fontFamily:'"JetBrains Mono", monospace',padding:'14px 0',caretColor:'#d0bcff'},'.cm-gutters':{backgroundColor:'#292725',color:'#938f89',border:'none',minWidth:'42px'},'.cm-activeLine,.cm-activeLineGutter':{backgroundColor:'#393532'},'.cm-selectionBackground':{backgroundColor:'#4f465d!important'},'.cm-line':{padding:'0 14px'},'.cm-tooltip':{backgroundColor:'#3c3835',border:'1px solid #5c5753'}})]}); const view=new EditorView({state,parent:host.current}); return()=>view.destroy()},[]);return <div className="editor" ref={host}/>}

function Canvas({selected,setSelected}){return <div className="canvas-wrap"><div className="canvas-tools"><button><ZoomOut size={17}/></button><span>82%</span><button><ZoomIn size={17}/></button><i/><button><Maximize size={17}/></button></div><div className="paper"><svg viewBox="0 0 820 540" role="img" aria-label="Anteprima dello schema di chiacchierino"><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#e8e3dc" strokeWidth=".7"/></pattern><filter id="shadow"><feDropShadow dx="0" dy="2" stdDeviation="5" floodOpacity=".12"/></filter></defs><rect width="820" height="540" rx="2" fill="#fffcf7"/><rect width="820" height="540" fill="url(#grid)" opacity=".7"/>
<g className={selected==='ring_center'?'selected shape':'shape'} onClick={()=>setSelected('ring_center')}><path d="M350 274 C350 207 420 170 490 274 C455 352 385 352 350 274Z" fill="#f5efff" stroke="#6750a4" strokeWidth="5"/><path d="M350 274 C350 207 420 170 490 274 C455 352 385 352 350 274Z" fill="none" stroke="#a98fd4" strokeWidth="1.5" strokeDasharray="3 10"/><circle cx="420" cy="190" r="5" className="attach"/><circle cx="485" cy="274" r="5" className="attach"/><circle cx="420" cy="335" r="5" className="attach"/><circle cx="355" cy="274" r="5" className="attach"/><path d="M414 188Q420 158 426 188" fill="none" stroke="#b3261e" strokeWidth="4" strokeLinecap="round"/><text x="420" y="374" textAnchor="middle">ring_center · 16U</text></g>
<g className={selected==='chain_right'?'selected shape':'shape'} onClick={()=>setSelected('chain_right')}><path d="M488 274 Q555 205 615 274" fill="none" stroke="#365f54" strokeWidth="5" strokeLinecap="round"/><path d="M488 274 Q555 205 615 274" fill="none" stroke="#b8cec7" strokeWidth="1.5" strokeDasharray="3 9"/><text x="553" y="220" textAnchor="middle">chain_right · 10U</text></g>
<g className={selected==='ring_right'?'selected shape':'shape'} onClick={()=>setSelected('ring_right')} transform="rotate(18 660 285)"><path d="M615 280 C617 230 665 203 710 280 C686 338 640 337 615 280Z" fill="#f5efff" stroke="#6750a4" strokeWidth="5"/><circle cx="615" cy="280" r="5" className="attach"/><text x="662" y="367" textAnchor="middle" transform="rotate(-18 662 367)">ring_right · 12U</text></g>
<g className="measure"><path d="M350 410H710"/><path d="M350 404V416M710 404V416"/><text x="530" y="432" textAnchor="middle">24 U</text></g></svg></div><div className="canvas-bottom"><button className="chip active"><Grid3X3 size={15}/> Griglia</button><button className="chip active"><Magnet size={15}/> Aggancio</button><button className="chip"><CircleDot size={15}/> Punti</button><span>Foglio A4 · Orizzontale</span></div></div>}

function App(){const [activePage,setActivePage]=useState(0); const [selected,setSelected]=useState('ring_center'); const [tab,setTab]=useState('canvas'); const [saved,setSaved]=useState(false); return <div className="app"><header><div className="brand"><div className="logo">T</div><div><strong>Tatting Studio</strong><span>Motivo primavera <i>•</i> Salvato automaticamente</span></div></div><div className="header-actions"><button className="icon"><Undo2/></button><button className="icon disabled"><Redo2/></button><span className="divider"/><button className="text-btn" onClick={()=>setSaved(true)}><Save/> Salva</button><button className="primary"><Download/> Esporta PNG</button><button className="avatar">AL</button></div></header>
<div className="workspace"><nav><button className="nav-active"><PencilRuler/><span>Editor</span></button><button><Layers3/><span>Oggetti</span></button><button><BookOpen/><span>Linguaggio</span></button><button><FileText/><span>Progetto</span></button><div/><button><Settings/><span>Impostazioni</span></button></nav>
<aside className="pages"><div className="aside-title"><div><span>PROGETTO</span><h2>Pagine</h2></div><button><Plus/></button></div><div className="page-list">{pages.map((p,i)=><button key={p.name} onClick={()=>setActivePage(i)} className={i===activePage?'active':''}><span className="page-num">{i+1}</span><span><b>{p.name}</b><small>{p.count} oggetti</small></span><MoreHorizontal/></button>)}</div><div className="tree-head"><span>OGGETTI</span><button><Search size={16}/></button></div><div className="tree"><div className="tree-root"><ChevronDown/><Layers3/><b>{pages[activePage].name}</b></div>{objects.map(o=>{const Icon=o.icon;return <button className={selected===o.id?'selected':''} onClick={()=>setSelected(o.id)} key={o.id}><span className="branch">└</span><Icon style={{color:o.color}}/><span><b>{o.id}</b><small>{o.kind}</small></span><Eye/><Lock className="muted"/></button>})}</div><button className="add-object"><Plus/> Inserisci oggetto <ChevronDown/></button></aside>
<main><div className="main-tabs"><button className={tab==='source'?'active':''} onClick={()=>setTab('source')}><Command/> Sorgente</button><button className={tab==='canvas'?'active':''} onClick={()=>setTab('canvas')}><PencilRuler/> Canvas</button><div/><span className="valid"><CheckCircle2/> Sintassi valida</span><button className="run"><Play/> Aggiorna anteprima</button></div><div className="split"><section className={tab==='source'?'code-pane expanded':'code-pane'}><div className="pane-title"><span><i/> SCHEMA.TAT</span><span>Lezer · Tatting 1.2</span></div><CodeEditor/><div className="status"><span>Ln 1, Col 1</span><span>UTF-8</span><span>4 oggetti</span></div></section><section className={tab==='canvas'?'preview expanded':'preview'}><div className="pane-title"><span>ANTEPRIMA</span><div><button><Share2/> Condividi</button><button><PanelRightClose/></button></div></div><Canvas selected={selected} setSelected={setSelected}/></section></div></main>
<aside className="properties"><div className="prop-head"><span>PROPRIETÀ</span><button><MoreHorizontal/></button></div><div className="selected-card"><div className="object-icon"><CircleDot/></div><div><small>RING</small><b>{selected}</b></div><span className="valid-dot">Valido</span></div><div className="section"><h3><ChevronDown/> Geometria</h3><label>Posizione <div className="coords"><span>X <b>420</b></span><span>Y <b>280</b></span></div></label><label>Nodi strutturali <div className="value"><b>16</b><span>U</span></div></label><label>Rotazione <div className="value"><b>0</b><span>°</span></div></label><label>Rotondità <input type="range" defaultValue="58"/><b>58</b></label></div><div className="section"><h3><ChevronDown/> Aspetto</h3><label>Tratto <div className="color"><i/><b>#6750A4</b></div></label><label>Spessore <div className="value"><b>2.5</b><span>px</span></div></label></div><div className="section"><h3><ChevronRight/> Punti di attacco <span>4</span></h3></div><div className="source-link"><FileText/><span>Definito alle righe <b>2–7</b></span><button>Vai al codice</button></div></aside></div>{saved&&<div className="snackbar"><CheckCircle2/> Progetto salvato correttamente <button onClick={()=>setSaved(false)}>Chiudi</button></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
